### PR TITLE
Add ruby 3.2 support

### PR DESCRIPTION
**Pull request by such**
## What? Why?

Allow ruby 3.2

## How was it tested?

Added ruby 3.2 to the test matrix

### CODE REVIEW

**Comment by splittingred** [comment]
Hey @such ! Unfortunately we're going to be blocked by https://github.com/protocolbuffers/protobuf/issues/11407 - once that is resolved, we can move forward with 3.2 support.

**Comment by such** [comment]
Hey @splittingred,

I'm not sure I understand the issue...
https://github.com/protocolbuffers/protobuf/issues/11407 is closed now. Do you think we can move forward?

**Comment by splittingred** [comment]
Hey @such! Unfortunately, grpc+protobuf do not yet support 3.2 in any _released_ versions. gruf typically _follows_ those releases (to maintain full support), so until grpc+protobuf have full 3.2 support across architectures released (they do not yet, ), we'll be blocked. 

Currently, AFAICT, grpc is not yet supported for arm64 architectures, which is a blocker - [this PR is merged](https://github.com/grpc/grpc/pull/31997) but unreleased. As soon as that's released, we'll be able to move forward with a gruf release supporting 3.2.

**Comment by splittingred** [comment]
This has now been merged in #182 - note that ARM macs will need an additional bundle config arg when installing (see PR).

**Pull request closed without merging**
